### ISSUE TITLE
spidev devices still don't show up

### ISSUE THREAD

**Issue by nlbutts** [gtjoseph/jetson-nano-support#2]
I'm running L4T 32.x version of L4T. I tried to run the flash-partitions.sh and it did flash various partitions, but I don't see any spidev messages in the kernel startup nor are there any /dev/spi devices.

I then tried to convert the DTB files in this repo to DTS files and looked through them. I see the additions to the SPI devices. Here is an excerpt from it:
`
	spi@7000d400 {
		compatible = "nvidia,tegra210-spi";
		reg = <0x0 0x7000d400 0x0 0x200>;
		interrupts = <0x0 0x3b 0x4>;
		iommus = <0x2b 0xe>;
		#address-cells = <0x1>;
		#size-cells = <0x0>;
		dmas = <0x4c 0xf 0x4c 0xf>;
		dma-names = "rx", "tx";
		nvidia,clk-parents = "pll_p", "clk_m";
		clocks = <0x21 0x29 0x21 0xf3 0x21 0xe9>;
		clock-names = "spi", "pll_p", "clk_m";
		resets = <0x21 0x29>;
		reset-names = "spi";
		status = "okay";
		num-cs = <0x2>;
		cs-gpios = <0x56 0x13 0x1 0x56 0x14 0x1>;
		linux,phandle = <0x10b>;
		phandle = <0x10b>;

		prod-settings {
			#prod-cells = <0x3>;

			prod {
				prod = <0x4 0xfff 0x0>;
			};

			prod_c_flash {
				status = "disabled";
				prod = <0x4 0x3f 0x7>;
			};

			prod_c_loop {
				status = "disabled";
				prod = <0x4 0xfff 0x44b>;
			};
		};

		spi@0 {
			#address-cells = <0x1>;
			#size-cells = <0x0>;
			compatible = "spidev";
			status = "okay";
			reg = <0x0>;
			spi-max-frequency = <0x3dfd240>;

			controller-data {
				nvidia,cs-setup-clk-count = <0x1e>;
				nvidia,cs-hold-clk-count = <0x1e>;
				nvidia,rx-clk-tap-delay = <0x1f>;
				nvidia,tx-clk-tap-delay = <0x0>;
			};
		};

		spi@1 {
			#address-cells = <0x1>;
			#size-cells = <0x0>;
			compatible = "spidev";
			status = "okay";
			reg = <0x1>;
			spi-max-frequency = <0x3dfd240>;

			controller-data {
				nvidia,cs-setup-clk-count = <0x1e>;
				nvidia,cs-hold-clk-count = <0x1e>;
				nvidia,rx-clk-tap-delay = <0x1f>;
				nvidia,tx-clk-tap-delay = <0x0>;
			};
		};
	};
`

But when the Nano boots, I don't see anything additional spi devices in the /proc/devicetree. For example, here is what is in /proc/device-tree/spi@7000d400:
`
nlbutts@jetson:/proc/device-tree/spi@7000d400$ ls
'#address-cells'   clocks       dma-names   interrupts   linux,phandle   nvidia,clk-parents   prod-settings   reset-names  '#size-cells'
 clock-names       compatible   dmas        iommus       name            phandle              reg             resets        status
`

I've tried to manually insmod spidev, but that doesn't work either.  Any ideas?

**Comment by gtjoseph** [comment]
That's odd.  It looks like the dtb isb't actually being loaded.

Go to 
https://github.com/gtjoseph/jetson-nano-support/releases/tag/sdcard
and download flash-dtb-update-2019-11-24.tar.gz.

Follow the instructions and run this on the nano itself.

**Comment by nlbutts** [comment]
That worked. Looking at your partition file:
declare -A partitions=(\
[RP1]='part_num=3;part_name=RP1;part_size=458752;part_file=tegra210-p3448-0000-p3449-0000-${dtb_id}.dtb.encrypt' \
[EBT]='part_num=4;part_name=EBT;part_size=589824;part_file=cboot.bin.encrypt' \
[WB0]='part_num=5;part_name=WB0;part_size=65536;part_file=warmboot.bin.encrypt' \
[LNX]='part_num=9;part_name=LNX;part_size=655360;part_file=boot.img.encrypt' \
[DTB]='part_num=10;part_name=DTB;part_size=458752;part_file=tegra210-p3448-0000-p3449-0000-${dtb_id}.dtb.encrypt' \
)

You are updating the boot image and warmboot. Did you update u-boot and warmboot or just the device-tree?

**Comment by gtjoseph** [comment]
u-boot had to be modified and recompiled because it, by default, will configure the SPI pins as GPIOs which will prevent any communications on the SPI pins.

I didn't do anything to warmboot but it does get modified during the signing process so I figured I'd better include it.
