### ISSUE TITLE
One or more files are corrupt or missing

### ISSUE THREAD

**Issue by TrueShadow97** [gtjoseph/jetson-nano-support#4]
Following the instructions given to the repo, I cloned it to my machine. There's no flashme.sh file in the root directory, but there is one in the /flash directory. However, when I try to execute it, I get the following error:
> md5sum: ./hash.md5: No such file or directory
> One or more files are corrupt or missing.
> 
> md5sum: ./hash.md5: No such file or directory

I'm running JetPack 4.2, if it is of any substance to the issue.

**Comment by gtjoseph** [comment]
Hmmm.  Sorry about that.  I'll take a look later today.

**Comment by gtjoseph** [comment]
Instead of cloning the repository, download the release tarball to the Nano...
https://github.com/gtjoseph/jetson-nano-support/releases/download/v1.0.2/flash-dtb-update-2019-12-09.tar.gz
Extract it, change to the flash-dtb-update-2019-12-09 directory and run flashme.sh

**Comment by TrueShadow97** [comment]
This worked, thank you very much. Will see if SPI is now in the device tree, but if it isn't, that's another issue already.
